# Generated by Django 3.0.3 on 2020-03-15 19:36

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots,
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    """
    Pada cada ABC (abstract base class), instanciar um MTI (multi table inheritance) com todos os atributos
    Salvar o MTI
    Associar os speakers do ABC no MTI
    Deletar o ABC
    :param apps:
    :param schema_editor:
    :return:
    """
    copy_src_to_dst(
        Source=apps.get_model('core', 'CourseOld'),
        Destination=apps.get_model('core', 'Course'),
    )


def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        Source=apps.get_model('core', 'Course'),
        Destination=apps.get_model('core', 'CourseOld'),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, backward_course_abc_to_mti)
    ]
